import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/components/Header'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='antialiased'>
      <body className="bg-blue-50">
        <div className='fixed top-0 z-50'> <Header />  </div>
        <div className='relative top-24 w-4/5 m-auto'>{children} </div>
      </body>
    </html>
  )
}